### ISSUE TITLE
标注中空行和错误

### ISSUE THREAD

**Issue by sidney1994** [ZhuiyiTechnology/AutoIE#1]
> 我看到在valid.txt中有一行，是空的，进行了标注，这个空在测试时会出现吗？  https://github.com/ZhuiyiTechnology/AutoIE/blob/668bba79de7fb1866c4a597494a5075faf0d2711/data/valid.txt#L2249

在标注中我还看到一处错误
https://github.com/ZhuiyiTechnology/AutoIE/blob/668bba79de7fb1866c4a597494a5075faf0d2711/data/valid.txt#L15455

**Comment by ZhuiyiTechnology** [comment]
第一处的空格是在影视剧标题中间的， 我们没有删除。 这个属于正常情况。不确定test集中是否出现。 我们做标注时如果一个实体中间有空格， 是不删除的。

第二处 晒 E-PER 已经修改了， 感谢指出
