### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by zhang-yunke** [ZhuiyiTechnology/AutoIE#3]
你好，我在按照readme中的步骤运行baseline的时候run.sh遇到了transformer包报如下错误，想请教一下原因（运行环境2080Ti 12G）
File "/home/xxx/anaconda3/envs/xxx/lib/python3.7/site-packages/torch/nn/modules/module.py", line 629, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by jma-code** [comment]
我们也遇到了这个问题，请问你们解决了吗

**Comment by zhang-yunke** [comment]
@jma-code 没有解决，希望官方可以解答一下 @ZhuiyiTechnology

**Comment by ZhuiyiTechnology** [comment]
这个错误是由 transformer这个包造成的， 具体的原因和修正方法， 我们正在定位。

**Comment by ZhuiyiTechnology** [comment]
请将 transformer 包的版本控制在 2.6.0， 不要安装2.8.0版本。  @ywwhxxtw @jma-code

**Comment by zhang-yunke** [comment]
@ZhuiyiTechnology 谢谢，已解决
